steps:
- id: 'Unit Tests'
  name: 'eu.gcr.io/ons-sdx-ci/sdx-gcp:1.3.1'
  script: |
    #!/usr/bin/env bash
    pip install -r requirements.txt
    pip install -r test-requirements.txt
    pytest -v --cov-report term-missing --disable-warnings --cov=app tests/
